### ISSUE TITLE
More venues

### ISSUE THREAD

**Issue by sirinath** [jvirtanen/juncture#1]
Is it possible to support more venues out of the box, perhaps borrowing from what the other projects you have been involved in has done.

**Comment by jvirtanen** [comment]
Of course! Do you have a need for some particular trading venue?

Past projects have taught me that the more trading venues a project supports, the more inertia it will add to maintaining the project. I myself have so far had need only for NASDAQ, therefore it is currently the only supported trading venue.

**Comment by jvirtanen** [comment]
I close this for now. If a need for a particular trading venue comes up, that can be handled then through a new, more specific issue.
